spring:
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888
      name: api-gateway
      profile: dev
      label: main

    gateway:
      routes[0]:
        id: client-service
        uri: lb://bank-client-microservice
        predicates:
          - Path=/api/v1/clients/**
      routes[1]:
        id: product-service
        uri: http://localhost:9003
        predicates:
          - Path=/api/v1/products/**
      routes[2]:
        id: transaction-service
        uri: lb://bank-transaction-microservice
        predicates:
          - Path=/api/v1/transactions/**
  security:
    user:
      name: user
      password: password

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem